import Phaser from "phaser";
import { generateTextures } from "../assets/generateTextures";
import { WIZARD_FRAME_KEYS } from "../gameplay/wizardAnimation";
import { groundIconKey, groundTilesetKey } from "../level/themes";

export class BootScene extends Phaser.Scene {
  constructor() {
    super("Boot");
  }

  preload(): void {
    // Relative paths (no leading slash) so assets resolve correctly whether
    // the app is served from a domain root (dev server) or a subpath (a
    // GitHub Pages project site) - see the `base` comment in vite.config.ts.
    for (const key of WIZARD_FRAME_KEYS) {
      this.load.image(key, `assets/wizard/${key.replace("wizard-", "")}.png`);
    }
    this.load.image("enemy-ghost-pillow", "assets/entities/ghost-pillow.png");
    this.load.image("goal-portal", "assets/entities/dream-portal.png");

    // Real Kenney "Pixel Platformer" (CC0) art for the grass/desert ground
    // themes, the brick/bounce blocks, and the bat/spike-crawler enemies —
    // see generateTextures.ts for why castle's tileset (no stone tile in
    // this pack) and the UI chrome stay procedural. Pre-composited to this
    // project's tile/entity sizes by a one-off prep script (source tiles
    // are 18px/24px native); see the "Real art" note in generateTextures.ts.
    this.load.image(groundTilesetKey("grass"), "assets/tiles/tileset-grass.png");
    this.load.image(groundIconKey("grass"), "assets/tiles/icon-grass.png");
    this.load.image(groundTilesetKey("desert"), "assets/tiles/tileset-desert.png");
    this.load.image(groundIconKey("desert"), "assets/tiles/icon-desert.png");
    this.load.image(groundTilesetKey("snow"), "assets/tiles/tileset-snow.png");
    this.load.image(groundIconKey("snow"), "assets/tiles/icon-snow.png");
    this.load.image("tile-brick-icon", "assets/tiles/icon-brick.png");
    this.load.image("tile-bounce-icon", "assets/tiles/icon-bounce.png");
    this.load.image("tile-water-icon", "assets/tiles/icon-water.png");
    this.load.image("enemy-bat", "assets/entities/bat.png");
    this.load.image("enemy-spike-crawler", "assets/entities/spike-crawler.png");
    this.load.image("enemy-golem", "assets/entities/golem.png");
    this.load.image("trophy", "assets/entities/trophy.png");
    this.load.image("chest", "assets/entities/chest.png");

    // Item icons (real Kenney art, except Feather — see generateTextures.ts).
    this.load.image("item-coin", "assets/items/coin.png");
    this.load.image("item-heart", "assets/items/heart.png");
    this.load.image("item-speed", "assets/items/speed.png");
    this.load.image("item-shield", "assets/items/shield.png");
    this.load.image("item-key", "assets/items/key.png");

    // Purely cosmetic decoration sprites (see editor/Palette.ts's "decor"
    // category) — no collision, no gameplay effect.
    for (const decor of ["bush", "tree", "cactus", "lamp", "cloud", "snowman", "sprout", "mushroom", "rocks"]) {
      this.load.image(`decor-${decor}`, `assets/decor/${decor}.png`);
    }
    // Perched (wings-folded) pose of the Bat enemy's art, reused here as a
    // purely decorative "sleeping bat" — not an animation frame for the
    // live enemy, which stays a single flying-pose sprite (see
    // EnemyBehaviors.ts; no per-enemy texture-swap animation exists yet).
    this.load.image("decor-bat", "assets/entities/bat-perched.png");

    // Parallax background layers (see gameplay/ParallaxBackground.ts and
    // level/backgrounds.ts for the theme-independent "background scene"
    // pool). Castle's starfield is generated directly at a large, fixed
    // 2048x476 size (no matching sky art in the pack) — see
    // generateTextures.ts. The pack's small 24x24 sky tiles
    // (grass/desert/icy/jungle) used to be baked up to that same size and
    // offered as scenes too, but even baked large they still read as an
    // obvious repeating grid of tiny icons up close — see backgrounds.ts's
    // docstring — so they were dropped from the pool entirely.

    // Original painted background scenes (not theme-tied — selectable for
    // any level via EditorUI's "Background: ▶" cycle button), generated by
    // scripts/generate-painted-backgrounds.py.
    for (const scene of ["pirate-cove", "overgrown-ruins", "snowy-peaks"]) {
      this.load.image(`bg-${scene}-far`, `assets/backgrounds/scenes/${scene}-far.png`);
      this.load.image(`bg-${scene}-near`, `assets/backgrounds/scenes/${scene}-near.png`);
    }
  }

  create(): void {
    generateTextures(this);
    this.scene.start("Menu");
  }
}
